---
title: "scRNA-seq Neonatal Lung Injury 2.2"
author: Shawyon Shirazi & Nick Negretti
date: 3/15/24
output: rmarkdown::github_document
---

# Analysis of the lung endothelium

## Load libraries and helper functions
```{r, results="hide", message = FALSE, load-libraries}
source("./helper_functions/globals.R")
source("./helper_functions/libraries.R")
source("./helper_functions/cluster.R")
source("./helper_functions/colors.R")

N_WORKERS <- 12
plan("multicore", workers = N_WORKERS)
```

## Load data from merge and clean pipeline
```{r}
endo <- readRDS("./data/checkpoint/post_sct_split_endo.rds")
```

## UMAP and clustering pt1
```{r, fig.width = 12}

endo <- cluster_pca_umap(endo,
                         k_param = 10,
                         dims_umap = 1:20,
                         dims_neighbors = 1:20,
                         cluster_res = 1.5,
                         algorithm = 4)

p_cluster <- DimPlot(endo,
                     label = TRUE) +
             umap_theme() +
             theme(aspect.ratio = 1)

endo_cluster <- p_cluster +
                plot_annotation("Endothelium")
ggsave("./data/checkpoint/endo/cluster1.png")
```

```{r}
marker_genes <- c("EPCAM", "PTPRC", "COL1A1", # Broad subtype
                  "PECAM1", "VWF", # Endo and vessel specific
                  "CCL21", "PROX1", "MMRN1", # Lymphatic
                  "CA4", "EDNRB", "APLN", # aCap
                  "FCN3", "IL7R", "CD36", "APLNR", # gCap
                  "HEY1", "GJA5", "DKK2", # Arterial
                  "COL15A1", "EBF1", "PLVAP", "SPRY1", # Systemic Venous
                  "ACKR1", # Venous
                  "CPE", "C7", "HDAC9", # Pulmonary Venous
                  "MKI67", "TOP2A", "CDC20") # Prolif and extra
endo_markers <- DotPlot(endo,
                        features = marker_genes) +
                theme(axis.text.x = element_text(angle = 45,
                                                 hjust = 1))
ggsave("./data/checkpoint/endo/markers1.pdf")
```

```{r metrics}
vlnplot_metrics <- VlnPlot(endo,
                           features = c("nCount_RNA",
                                        "nCount_SCT",
                                        "percent.mt",
                                        "percent.rb"),
                           group.by = "seurat_clusters")
ggsave("./data/checkpoint/endo/metrics1.png",
       width = 15)
```

```{r}
N_WORKERS <- 20
plan("multicore", workers = N_WORKERS)
endo_sub_sct <- SCTransform(subset(endo,
                                   idents = c(26),
                                   invert = TRUE),
                            variable.features.n = 2000,
                            batch_var = "dataset",
                            conserve.memory = TRUE,
                            vars.to.regress = c("percent.mt",
                                                "percent.rb"),
                            method = "glmGamPoi",
                            ncells = NULL)
var_feat_backup2 <- VariableFeatures(endo_sub_sct)
```

## UMAP and clustering pt2
```{r, fig.width = 12}
endo_sub_sct <- cluster_pca_umap(endo_sub_sct,
                                 k_param = 5,
                                 dims_umap = 1:15,
                                 dims_neighbors = 1:15,
                                 cluster_res = 1,
                                 algorithm = 4)

p_cluster <- DimPlot(endo_sub_sct,
                     label = TRUE) +
             umap_theme() +
             theme(aspect.ratio = 1)

endo_cluster2 <- p_cluster +
                 plot_annotation("Endothelium")
ggsave("./data/checkpoint/endo/cluster2.png")
```

```{r}
marker_genes <- c("EPCAM", "PTPRC", "COL1A1",
                  "PECAM1", "VWF",
                  "CCL21", "PROX1", "MMRN1",
                  "CA4", "EDNRB", "APLN",
                  "FCN3", "IL7R", "CD36", "APLNR",
                  "HEY1", "GJA5", "DKK2",
                  "COL15A1", "EBF1", "PLVAP", "SPRY1",
                  "ACKR1",
                  "CPE", "C7", "HDAC9",
                  "MKI67", "TOP2A", "CDC20", "ANKRD1")
endo_markers2 <- DotPlot(endo_sub_sct,
                         features = marker_genes) +
                 theme(axis.text.x = element_text(angle = 45,
                                                  hjust = 1))
ggsave("./data/checkpoint/endo/markers2.pdf")
```


```{r metrics}
vlnplot_metrics <- VlnPlot(endo_sub_sct,
                           features = c("nCount_RNA",
                                        "nCount_SCT",
                                        "percent.mt",
                                        "percent.rb"),
                           group.by = "seurat_clusters")
ggsave("./data/checkpoint/endo/metrics2.png",
       width = 15)
```


```{r}
N_WORKERS <- 20
plan("multicore", workers = N_WORKERS)
endo_sub2_sct2 <- SCTransform(subset(endo_sub_sct,
                                     idents = c(8, 22, 24, 27),
                                     invert = TRUE),
                              variable.features.n = 2000,
                              batch_var = "dataset",
                              conserve.memory = TRUE,
                              vars.to.regress = c("percent.mt",
                                                  "percent.rb"),
                              method = "glmGamPoi",
                              ncells = NULL)
var_feat_backup2 <- VariableFeatures(endo_sub2_sct2)
```

## UMAP and clustering pt3
```{r, fig.width = 12}
endo_sub2_sct2 <- cluster_pca_umap(endo_sub2_sct2,
                                   k_param = 5,
                                   dims_umap = 1:15,
                                   dims_neighbors = 1:15,
                                   cluster_res = 1,
                                   harmonysigma = 0.4,
                                   algorithm = 4)

p_cluster <- DimPlot(endo_sub2_sct2,
                     label = TRUE) +
             umap_theme() +
             theme(aspect.ratio = 1)

endo_cluster2 <- p_cluster +
                 plot_annotation("Endothelium")
ggsave("./data/checkpoint/endo/cluster3.png")
```

```{r}
marker_genes <- c("EPCAM", "PTPRC", "COL1A1",
                  "PECAM1", "VWF",
                  "CCL21", "PROX1", "MMRN1",
                  "CA4", "EDNRB", "APLN",
                  "FCN3", "IL7R", "CD36", "APLNR",
                  "HEY1", "GJA5", "DKK2",
                  "COL15A1", "EBF1", "PLVAP", "SPRY1",
                  "ACKR1",
                  "CPE", "C7", "HDAC9",
                  "MKI67", "TOP2A", "CDC20", "ANKRD1")
endo_markers2 <- DotPlot(endo_sub2_sct2,
                         features = marker_genes) +
                 theme(axis.text.x = element_text(angle = 45,
                                                  hjust = 1))
ggsave("./data/checkpoint/endo/markers3.pdf")
table(endo_sub2_sct2$seurat_clusters)
```

```{r metrics}
DimPlot(endo_sub2_sct2,
        group.by = "celltype")
vlnplot_metrics <- VlnPlot(endo_sub2_sct2,
                           features = c("nCount_RNA",
                                        "nCount_SCT",
                                        "percent.mt",
                                        "percent.rb"),
                           group.by = "seurat_clusters")
ggsave("./data/checkpoint/endo/metrics3.png", width = 15)

```

```{r}
N_WORKERS <- 20
plan("multicore", workers = N_WORKERS)
endo_sub3_sct3 <- SCTransform(subset(endo_red_res,
                                     idents = c(6, 29),
                                     invert = TRUE),
                              variable.features.n = 2000,
                              batch_var = "dataset",
                              conserve.memory = TRUE,
                              vars.to.regress = c("percent.mt",
                                                  "percent.rb"),
                              method = "glmGamPoi",
                              ncells = NULL)
var_feat_backup2 <- VariableFeatures(endo_sub3_sct3)
```

## UMAP and clustering pt4
```{r, fig.width = 12}
endo_sub3_sct3 <- cluster_pca_umap(endo_sub3_sct3,
                                   k_param = 5,
                                   dims_umap = 1:15,
                                   dims_neighbors = 1:15,
                                   cluster_res = 1,
                                   harmonysigma = 0.4,
                                   algorithm = 4)

p_cluster <- DimPlot(endo_sub3_sct3,
                     label = TRUE) +
             umap_theme() +
             theme(aspect.ratio = 1)

endo_cluster2 <- p_cluster +
                 plot_annotation("Endothelium")
ggsave("./data/checkpoint/endo/cluster4.png")
```

```{r}
marker_genes <- c("EPCAM", "PTPRC", "COL1A1",
                  "PECAM1", "VWF",
                  "CCL21", "PROX1", "MMRN1",
                  "CA4", "EDNRB", "APLN",
                  "FCN3", "IL7R", "CD36", "APLNR",
                  "HEY1", "GJA5", "DKK2",
                  "COL15A1", "EBF1", "PLVAP", "SPRY1",
                  "ACKR1",
                  "CPE", "C7", "HDAC9",
                  "MKI67", "TOP2A", "CDC20", "ANKRD1")
endo_markers2 <- DotPlot(endo_sub3_sct3,
                         features = marker_genes) +
                 theme(axis.text.x = element_text(angle = 45,
                                                  hjust = 1))
ggsave("./data/checkpoint/endo/markers4.pdf")
table(endo_sub3_sct3$seurat_clusters)
```

## Save the DEgenes per cluster
```{r}
N_WORKERS <- 20
plan("multicore", workers = N_WORKERS)
filename <- "./data/checkpoint/pre_annotated_endo_for_deg.rds"
if (!file.exists(filename)) {
  markers <- parallel_find_all_markers(endo_sub3_sct3)

  names(markers) <- levels(Idents(endo_sub3_sct3))
  saveRDS(markers, filename)
} else {
  markers <- readRDS(filename)
}

wb_markers_names <- levels(Idents(endo_sub3_sct3))
wb_markers <- createWorkbook()
for (idx in seq_along(wb_markers_names)){
  addWorksheet(wb_markers,
               wb_markers_names[idx])
  writeData(wb_markers,
            wb_markers_names[idx],
            markers[[idx]],
            rowNames = TRUE)
}
saveWorkbook(wb_markers,
             file = "./data/checkpoint/endo_cluster_deg.xlsx",
             overwrite = TRUE)
```

## Annotation
```{r}
endo_relabel <- endo_sub3_sct3
endo_relabel$louvain <- as.factor(endo_sub3_sct3$seurat_clusters)
endo_relabel$celltype <- as.factor(endo_sub3_sct3$seurat_clusters)

idxes <- levels(endo_relabel$celltype)
labels <- rep("gCap", length(levels(endo_relabel$celltype)))
labels[idxes %in% c(5, 8, 11, 17)] <- "aCap"
labels[idxes %in% c(9)] <- "abCap"
labels[idxes %in% c(4)] <- "Arterial EC"
labels[idxes %in% c(1, 16)] <- "Pulmonary venous EC"
labels[idxes %in% c(6)] <- "Lymphatic"
labels[idxes %in% c(15, 20)] <- "Systemic venous EC"

levels(endo_relabel$celltype) <- labels
endo_relabel$celltype <- ordered(as.factor(endo_relabel$celltype),
                                 c("gCap",
                                   "aCap",
                                   "abCap",
                                   "Arterial EC",
                                   "Pulmonary venous EC",
                                   "Systemic venous EC",
                                   "Lymphatic"
                                 ))
```

## Save data for next step merge
```{r}
plan("multicore", workers = N_WORKERS)
filename <- "./data/checkpoint/annotated_endo.rds"
saveRDS(endo_relabel,
        filename,
        compress = "gzip")
```

## Save h5ad for cellxgene visualization
```{r}
writeAnnData <- function(seurat_obj, filename) {

  anndata::AnnData(X = t(GetAssayData(seurat_obj,
                                      slot = "data",
                                      assay = "SCT")),
    var = data.frame(gene = rownames(seurat_obj),
                     row.names = rownames(seurat_obj)),
    obs = data.frame(louvain = as.character(Idents(seurat_obj)),
                     dataset = as.character(seurat_obj$dataset),
                     seq_run = as.character(seurat_obj$orig.ident),
                     age = as.character(seurat_obj$age),
                     condition = as.character(seurat_obj$condition),
                     annotation = as.character(seurat_obj$celltype),
                     broad_condition = as.character(seurat_obj$broad_condition),
                     row.names = colnames(seurat_obj),
                     total_counts = as.numeric(seurat_obj$nCount_SCT),
                     pct_mito = as.numeric(seurat_obj$percent.mt),
                     pct_ribo = as.numeric(seurat_obj$percent.rb)),
    obsm = list(X_umap = matrix(Embeddings(seurat_obj,
                                           reduction = "umap"),
                                ncol = 2)),
    raw = anndata::AnnData(X = t(GetAssayData(seurat_obj,
                                              slot = "counts",
                                              assay = "RNA")),
                               var = data.frame(gene = rownames(seurat_obj@assays$RNA),
                                                row.names = rownames(seurat_obj@assays$RNA)))
  )$write_h5ad(filename,
               compression = "gzip")
}

filename <- "./data/checkpoint/endo_only.h5ad"
writeAnnData(endo_relabel,
             filename)
```